<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css"/>
    <link rel="stylesheet" href="/css/styles.css"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script type="text/javascript">
        var chart = null, series = [];
        <?php foreach ($sites as $site => $visits) : ?>
        series.push({name: '<?= $site ?>', data: []});
        <?php endforeach ?>
    </script>
    <script src="/js/default.js"></script>
</head>
<body>
<table align="center">
    <tr>
        <th class="th">Site</th>
        <th class="th">Page Views</th>
        <th class="th">Latest</th>
        <th>Average</th>
    </tr>
    <?php foreach ($sites as $site => $visits) : ?>
        <tr id="<?= 'tr_' . md5($site) ?>">
            <td class="td_left"><?= $site ?></td>
            <td class="td_center"><?= number_format($visits) ?></td>
            <td class="td_center">-</td>
            <td class="td_center">-</td>
        </tr>
    <?php endforeach ?>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3" class="td_center" id="status"></td>
    </tr>
</table>
<div id="container" style="height: 400px"></div>
</body>
</html>